---
knit: (function(input_file, encoding) {
  out_dir <- 'docs/R';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file='../multinomial-logistic-regression.md') })
output:
  html_document:
    highlight: tango
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, fig.path="../img/multinomial-logistic-regression/",
                      fig.width=6, fig.height=4,
                      fig.show='hold', fig.align='center')
options(width=100)
```

# Multinomial Logistic Regression in R

For this example we will be using [this data set](https://github.com/tylerbg/DLC_stat_resources/tree/master/docs/R/dat/cheese.csv) provided by the [STAT 504 Analysis of Discrete Data](https://online.stat.psu.edu/stat504/lesson/8/8.1) course.

The data set includes three variables:


```{r}
teach <- read.csv("../../dat/teaching-methods.csv")

head(teach)

library(tidyverse)

teach_long <- teach %>% group_by_all() %>%
  summarize(n_subject = n()) %>%
  pivot_wider(names_from = Subject,
              values_from = n_subject,
              values_fill = 0)

library(nnet)
teach_mlr <- multinom(Subject ~ ., data = teach)

teach_mlr <- multinom(cbind(Arts, Math, Science) ~ ., data = teach_long)

library(VGAM)
teach_mlr <- vglm(Subject ~ ., data = teach, family = multinomial)

teach_mlr <- vglm(cbind(Arts, Math, Science) ~ ., data = teach_long, family = multinomial)

summary(teach_mlr)

anova(teach_mlr, type = 3, test = "LR")

exp(coef(teach_mlr))
exp(confint(teach_mlr))


logLik(teach_mlr)


# pearson test for lack of fit
e = residuals(teach_mlr, type = 'pearson')
x2 = sum(e^2)
1 - pchisq(x2, df)

# deviance test for lack of fit
g2 = deviance(teach_mlr)
df = df.residual(teach_mlr)
1 - pchisq(g2, df)

library(car)
vif(teach_mlr)
plot(teach_mlr)
```



```{r}
iris %>% head()

iris_mlr <- vglm(Species ~ ., data = iris, family = multinomial)
iris_mlr <- multinom(Species ~ ., data = iris)

summary(iris_mlr)
logLik(iris_mlr)

```






```{r}
cheese %>%
  pivot_wider(names_from = Cheese, values_from = Count)
```

