---
knit: (function(input_file, encoding) {
  out_dir <- 'docs/R';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file='ordinal-logistic-regression.md') })
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      fig.path = "img/ordinal-logistic-regression/",
                      fig.width = 6, fig.height = 4,
                      fig.show = 'hold', fig.align = 'center')
options(width=100)
```

# Ordinal Logistic Regression (OLR)

```{r}
satisfaction <- read.csv("dat/patient_satisfaction.csv")
```

```{r}
head(satisfaction)
str(satisfaction)

## Order the response variable
satisfaction$Return.Appointment <- ordered(satisfaction$Return.Appointment,
                                           levels = c("Unlikely", "Somewhat Likely", "Very Likely"))

str(satisfaction)

library(MASS)

fit <- polr(Return.Appointment ~ Distance + I(Distance^2), data = satisfaction)

summary(fit)


## Get table of coefficients
coef_table <- coef(summary(fit))

## Estimate and print p-values
p <- pnorm(abs(coef_table[, "t value"]), lower.tail = FALSE) * 2
coef_table <- cbind(coef_table, "p value" = round(p, 4))

coef_table


table(satisfaction$Return.Appointment, predict(fit))

## Goodness of fit
library(generalhoslem)

lipsitz.test(fit)

logitgof(satisfaction$Return.Appointment, fitted(fit))

pulkrob.chisq(fit, c("Distance"))
pulkrob.deviance(fit, c("Distance"))
```



```{r}
wine <- read.csv("dat/winequality-red.csv")

head(wine)
str(wine)

wine$quality <- ordered(wine$quality)
```

```{r}
library(MASS)

fit <- polr(quality ~ ., data = wine)

summary(fit)

## Get table of coefficients
coef_table <- coef(summary(fit))

## Estimate and print p-values
p <- pnorm(abs(coef_table[, "t value"]), lower.tail = FALSE) * 2
coef_table <- cbind(coef_table, "p value" = round(p, 4))

coef_table


fit.tab <- table(actual = wine$quality, predicted = predict(fit))
fit.tab

sum(diag(fit.tab)) / sum(fit.tab)

## Goodness of fit
library(generalhoslem)

lipsitz.test(fit)

logitgof(wine$quality, fitted(fit))

pulkrob.chisq(fit, c("density"))
pulkrob.deviance(fit, c("density"))
```

