---
knit: (function(input_file, encoding) {
  out_dir <- '/docs/Info';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file='../common-R-packages.md') })
output:
  html_document:
    highlight: tango
    css: style.scss
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      fig.path = "../img/common-R-packages/",
                      fig.width = 6, fig.height = 4,
                      fig.show = 'hold', fig.align = 'center')
options(width=100)
```

# Common R Packages

<table style="width:100%">
  <tbody>
    <tr>
      <td colspan=3 style="font-size:150%;"><center><b>Data Handling and Manipulation</b></center></td>
    </tr>
    <tr>
      <td><b>Package</b></td>
      <td><b>Main use</b></td>
      <td><b>Sample functions</b></td>
    </tr>
    <!-- dplyr -->
    <tr>
      <td><a href="https://dplyr.tidyverse.org/">dplyr</a></td>
      <td>data manipulation</td>
      <td><code>mutate()</code> – adds new variables using functions on existing variables.<br>
<code>select()</code> – picks variables (columns) based on their name.<br>
<code>filter()</code> picks rows based on their values.<br>
<code>summarize()</code> – reduced multiple values down to a single summary.<br>
<code>arrange()</code> – changes the ordering of rows.</td>
    </tr>
    <!-- forcats -->
    <tr>
      <td><a href="https://forcats.tidyverse.org/">forcats</a></td>
      <td>handling categorical variables</td>
      <td><code>fct_reorder()</code> – reorders a factor by another variable.<br>
<code>fct_relevel()</code> – changes the order of factors manually.
</td>
    </tr>
    <!-- lubridate-->
    <tr>
      <td><a href="https://lubridate.tidyverse.org/">lubridate</a></td>
      <td>tools to work with date-time data</td>
      <td><code>now()</code> – current time in time zone.</td>
    </tr>
    <!-- purrr -->
    <tr>
      <td><a href="https://purrr.tidyverse.org/">purrr</a></td>
      <td>tools for working with vectors and functions</td>
      <td><code>map()</code> – allows you to replace many ‘for’ loops with code that is both more succinct and easier to read.</td>
    </tr>
    <!-- readr -->
    <tr>
      <td><a href="https://readr.tidyverse.org/">readr</a></td>
      <td>read data files (csv, tsv, etc.) in tidy format</td>
      <td><code>read_csv()</code> – reads .csv files and loads them as tibbles.</td>
    </tr>
    <!-- stringr -->
    <tr>
      <td><a href="https://stringr.tidyverse.org/">stringr</a></td>
      <td>working with strings</td>
      <td><code>str_replace()</code> – replaces matching text in a string with new text.<br>
<code>str_extract()</code> – extracts matching text from a string.<br>
<code>str_split()</code> – splits strings into multiple strings.
</td>
    </tr>
    <!-- tibble -->
    <tr>
      <td><a href="https://tibble.tidyverse.org/">tibble</a></td>
      <td>data classification and handling</td>
      <td><code>tibble()</code> – constructs a data frame with special behaviors, such as enhanced printing.</td>
    </tr>
    <!-- tidyr -->
    <tr>
      <td><a href="https://tidyr.tidyverse.org/">tidyr</a></td>
      <td>data cleaning (creating tidy data)</td>
      <td><code>pivot_longer()</code> and <code>pivot_wider()</code> – convert between long and wide formats.<br>
<code>drop_na()</code> – removes rows with missing values.
</td>
    </tr>
    <tr>
      <td colspan=3 style="font-size:150%;"><center><b><br><br>Data Visualization</b></center></td>
    </tr>
    <tr>
      <td><b>Package</b></td>
      <td><b>Main use</b></td>
      <td><b>Sample functions</b></td>
    </tr>
    <!-- ggplot2 -->
    <tr>
      <td><a href="https://ggplot2.tidyverse.org/">ggplot2</a></td>
      <td>data visualization</td>
      <td><code>ggplot()</code> – system for declaratively creating graphics, based on “The Grammar of Graphics.”</td>
    </tr>
    <!-- gridExtra -->
    <tr>
      <td><a href="https://rdrr.io/cran/gridExtra/">gridExtra</a></td>
      <td>working with graphical objects (grobs) on a grid</td>
      <td><code>arrangeGrob</code> - arrange multiple grobs on a page.</td>
    </tr>
    <!-- xtable -->
    <tr>
      <td><a href="https://rdrr.io/cran/xtable/">xtable</a></td>
      <td>formatting tables into LaTeX and HTML</td>
      <td><code>xtable</code> - convert an R object into an xtable object that can be printed as LaTeX or HTML</td>
    </tr>
    <tr>
      <td colspan=3 style="font-size:150%;"><center><b><br><br>Statistical Analysis</b></center></td>
    </tr>
    <tr>
      <td><b>Package</b></td>
      <td><b>Main use</b></td>
      <td><b>Sample functions</b></td>
    </tr>
    <!-- car -->
    <tr>
      <td><a href="https://cran.r-project.org/web/packages/car/car.pdf">car</a></td>
      <td>expands statistical toolset for regression and analysis of variance models</td>
      <td><code>Anova()</code> – calculates type 2 or type 3 sum of square tables.
<code>vif()</code> – calculates variance inflation factors to assess multicollinearity.
</td>
    </tr>
    <!-- caret -->
    <tr>
      <td><a href="https://rdrr.io/cran/caret/man/">caret</a></td>
      <td>tools for predictive modeling</td>
      <td><code>train()</code> – fits predictive models over different tuning parameters</td>
    </tr>
    <!-- emmeans & multcomp -->
    <tr>
      <td><a href="https://rdrr.io/cran/emmeans/man/">emmeans</a><br>
      <a href="https://rdrr.io/cran/multcomp/man/">multcomp</a></td>
      <td>tools for multiple comparison testing</td>
      <td><code>emmeans()</code> – calculates estimated marginal means for specified factors or factor combinations in a linear model; and optionally, comparisons or contrasts among them.<br>
<code>glht()</code> – general linear hypotheses and multiple comparisons for parametric models, including generalized linear models, linear mixed effects models, and survival models</td>
    </tr>
    <!-- lme4 & nlme -->
    <tr>
      <td><a href="https://rdrr.io/cran/lme4/man/">lme4</a><br>
      <a href="https://rdrr.io/cran/nlme/man/">nlme</a></td>
      <td>linear and non-linear mixed effect modeling</td>
      <td><code>lmer()</code> – fits linear mixed models.<br>
<code>glmer()</code> – fits generalized linear mixed models.<br>
<code>nlme()</code> – fits non-linear mixed models.
</td>
    </tr>
    <!-- rstatix -->
    <tr>
      <td><a href="https://rdrr.io/cran/rstatix/man/">rstatix</a></td>
      <td>pipe-friendly framework for performing basic statistical tests</td>
      <td><code>adjust_pvalue()</code> – adds and adjusted p-value into a data frame.<br>
<code>add_significance()</code> – adds p-value significance symbols to a data frame.
</td>
    </tr>
  </tbody>
</table>