---
knit: (function(input_file, encoding) {
  out_dir <- 'docs/JMP';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file='../repeated-measures-ANOVA.md') })
output:
  html_document:
    highlight: tango
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, results = 'hold',
                      fig.path = "../img/repeated-measures-ANOVA/",
                      fig.width = 6, fig.height = 4,
                      fig.show = 'hold', fig.align = 'center')
options(width=100)
```

# [Repeated measures ANOVA](https://repub.github.io/DLC_statistical_guides/docs/Info/repeated-measures-ANOVA) in `JMP`

In this guide we will be using a data set provided by [STAT 510 - Applied Time Series Analysis](https://online.stat.psu.edu/stat510/lesson/10/10.1), which contains observations from an experiment designed to detect phlebitis (venous inflammation) by measuring temperature during intravenous administration of a drug of interest in the ear of animals over time.  The data set has four variables:

* *Animal* - the unique identifier for the 15 animals tested.
* *Treatment* - one of three treatments administered:
  * the *drug* in a carrier solution,
  * only *carrier* solution, or
  * *saline* solution.
* *Time* - the time point in minutes when the temperature was recorded.
* *Y* - the difference in temperature between the treated and untreated ears of the animal.

After loading in the data table we should check that each variable is set to the modeling type we want.  To start, we will want both the *Animal* and *Treatment* variables to be set as *Nominal* and *Time* and *Y* as *Continuous*.  To change the variable type, right-click on the column of interest and select `Column Info...`, then in the pop up window you can use the drop-down list next to `Modeling Type` to change the type of variable.

