---
  knit: (function(input_file, encoding) {
    out_dir <- 'docs/R';
    rmarkdown::render(input_file,
                      encoding=encoding,
                      output_file='ANCOVA.md') })
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      fig.path = "img/ANCOVA/",
                      fig.width = 6, fig.height = 4,
                      fig.show = 'hold', fig.align = 'center')
options(width = 100)
```

# ANCOVA

```{r read_rye}
rye <- read.csv("dat/Rye-ANCOVA-2008.csv", stringsAsFactors = TRUE)
```

```{r rye_lm}
rye.lm <- lm(RyeDMg ~ Tdate + Plant, data = rye)

summary(rye.lm)
```

```{r rye_plot}
ggplot(rye, aes(x = factor(Tdate), y = RyeDMg, color = Plant)) +
  geom_point(alpha = 0.55, position = position_dodge(width = 0.35), size = 3) +
  theme_bw() +
  labs(x = "Days from the beginning of the growing season (April 15)",
       y = bquote("Rye biomass"~(g/m^2))) +
  scale_color_manual(values = c("steelblue3", "tomato3"))
```

```{r}
summary(aov(rye.lm))
```

