---
  knit: (function(input_file, encoding) {
    out_dir <- 'docs/R';
    rmarkdown::render(input_file,
                      encoding=encoding,
                      output_file='MANOVA.md') })
output: github_document
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      fig.path = "img/MANOVA/",
                      fig.width = 6, fig.height = 4,
                      fig.show = 'hold', fig.align = 'center')
options(width = 100)
```

# MANOVA

[Example dataset from PSU STAT 505](https://online.stat.psu.edu/stat505/lesson/8/8.4)

```{r load_data}
pottery <- read.csv("dat/pottery.csv", stringsAsFactors = TRUE)
```


```{r MANOVA_plot, echo = FALSE}
#### Convert dataset to long & add full names
library(tidyverse)
pottery.long <- pivot_longer(pottery, Al:Na)
pottery.long$Site <- as.character(pottery.long$Site)
pottery.long <- pottery.long %>% mutate(Site = recode(Site,
                                      "L" = "Llanedyrn",
                                      "C" = "Caldicot",
                                      "I" = "Isle Thorns",
                                      "A" = "Ashley Rails"))
pottery.long$Site <- as.factor(pottery.long$Site)

ggplot(pottery.long, aes(x = name, y = value, color = Site)) +
  geom_point(alpha = 0.55, position = position_dodge(0.55), size = 3) +
  theme_bw() +
  labs(x = "Element", y = "Abundance (log10(ppm))") +
  scale_y_log10() +
  scale_color_manual(values = c("steelblue3", "goldenrod3", "tomato1", "forestgreen")) +
  theme(legend.position = "bottom")
```



```{r MANOVA}
pottery.manova <- manova(cbind(Al, Fe, Mg, Ca, Na) ~ Site, data = pottery)

summary(pottery.manova)
```

```{r ANOVA_summaries}
summary.aov(pottery.manova)
```

```{r}
summary.lm(pottery.manova)
```



### Fit a MANOVA

```{r}
summary(iris)
```

```{r}
library(tidyverse)

iris.long <- pivot_longer(iris, Sepal.Length:Petal.Width)
iris.long$name <- gsub("\\.", " ", iris.long$name)

ggplot(iris.long, aes(x = name, y = value, color = Species)) +
  geom_boxplot(outlier.shape = NULL) +
  geom_jitter(alpha = 0.55, position = position_jitterdodge(dodge.width = 0.75)) +
  theme_bw() +
  labs(x = NULL) +
  scale_color_brewer(palette = "Set2")
  theme(legend.position = "bottom")

```


```{r}
iris.manova <- manova(cbind(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) ~ Species,
                      data = iris)

summary(iris.manova)
```

```{r}
summary.aov(iris.manova)
```


```{r}
iris.aov <- aov(Sepal.Width ~ Species, data = iris)
TukeyHSD(iris.aov)
```






# MANOVA with the Car Ratings data set

```{r}
ratings <- read.csv("dat/Car_Lock_Ratings.csv", header = TRUE, stringsAsFactors = TRUE)
```

```{r}
head(ratings)
str(ratings)
```

```{r}
ratings.manova <- manova(cbind(Usability.Rating, Quality.Rating) ~ Method * Plant, data = ratings)

summary(ratings.manova, test = "Wilks")


summary(car::Manova(ratings.manova, type = 3))
```

```{r}
summary.aov(ratings.manova)
```

