---
knit: (function(input_file, encoding) {
  out_dir <- 'docs/Info';
  rmarkdown::render(input_file,
    encoding=encoding,
    output_file='two-proportions.md') })
output: github_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Comparing Two Proportions

&emsp;Sometimes when we sample data from two populations we are interested in whether those two populations differ on some binary (only two outcomes) variable.  For example, we may be interested if Democrat and Republican senators vote differently (either yes or no) on a bill, or whether smokers and non-smokers believe that cigarettes should be taxed to fund health care (agree or disagree).  For these questions we can compare the population proportions with the following hypotheses:

&emsp;**Null hypothesis:** The proportions of the two variables are the equal.
<center><i>H<sub>0</sub>: p<sub>1</sub> = p<sub>2</sub></i></center>
<br>

&emsp;<b>Alternative hypothesis:</b> The proportions of the two variables are not equal.
<br>
<center><i>H<sub>A</sub>: p<sub>1</sub> &ne; p<sub>2</sub></i></center>
<br>

&emsp;To statistically test the equality of two proportions the following assumptions should be valid.

- The data was gathered by **simple random sampling**
- The two samples are **independent**
- Both groups follow a **binomial distribution**

&emsp;To compare the proportions, a z-statistic is first calculated in the equation:

<div class="center">

$$Z = \frac{(\hat{p_1} - \hat{p_2})}{\sqrt{\hat{p}(1 - \hat{p})(\frac{1}{n_1} + \frac{1}{n_2)}}}$$
</div>