---
knit: (function(input_file, encoding) {
    out_dir <- 'docs';
    rmarkdown::render(input_file,
                      encoding=encoding,
                      output_file='InsectSprays_Analysis') })
output: github_document
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, fig.path="imgs/InsectSprays_Analysis/",
                      fig.width=6, fig.height=4,
                      fig.show='hold', fig.align='center')
options(width=100)
```

# Analysis of the `InsectSprays` dataset

```{r}
?InsectSprays
```

```{r}
summary(InsectSprays)
```

```{r}
library(ggplot2)

ggplot(InsectSprays, aes(x=count)) +
  geom_histogram(bins=18) +
  theme_bw()
```

```{r}
ggplot(InsectSprays, aes(x=spray, y=count, fill=spray)) +
  geom_boxplot() +
  theme_bw()
```

```{r}
insect.aov <- aov(count~spray, data=InsectSprays)

summary(insect.aov)
```

```{r}
(insect.tukey <- TukeyHSD(insect.aov))

plot(insect.tukey)
```

```{r}
library(rstatix)
insect.tukey <- tukey_hsd(InsectSprays, count~spray)

insect.tukey
```

```{r}
library(ggpubr)

insect.boxplot <- ggboxplot(InsectSprays, x="spray", y="count", fill="spray")

insect.tukey <- insect.tukey %>%
  add_xy_position(x="spray")

insect.boxplot + stat_pvalue_manual(insect.tukey, label="p.adj.signif",
                                    hide.ns=TRUE)
```

```{r}
insect.boxplot <- ggplot(InsectSprays, aes(x=spray, y=count, fill=spray)) +
  geom_boxplot()

insect.coords <- with(InsectSprays, boxplot(count~spray, plot=FALSE))

ptt.rslt <- with(InsectSprays, pairwise.t.test(count, spray, pool.sd = FALSE))

library(multcomp)

# Perform Tukey HSD and get letters which show statistical significance
insect.tukey <- glht(insect.aov, linfct=mcp(spray="Tukey"))
ltrs <- cld(insect.tukey)$mcletters$monospacedLetters # Get letters
ltrs <- gsub(" ", "", ltrs) # Remove spaces

# Build dataframe with letters and coordinates to plot them
ltrs.df <- data.frame(x=c(1:length(levels(InsectSprays$spray))),
                      y=insect.coords$stats[5, ],
                      cbd=ltrs,
                      spray=names(ltrs))

# Get the max y-value to use with nudge_y for letter positioning
y.max <- max(layer_scales(insect.boxplot)$y$range$range)

# Plot boxplots using geom_text to add compact letter displays
insect.boxplot +
  geom_text(data=ltrs.df, aes(x=x, y=y, label=cbd), nudge_y=y.max*0.05) +
  labs(title="Effectiveness of Insect Sprays",
       subtitle=paste("ANOVA p-value =", summary(insect.aov)[[1]]$`Pr(>F)`[1]),
       x="Spray", y="Insect Count") +
  theme_bw(base_size=12) +
  theme(legend.position="")
```

