---
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,  
    encoding=encoding,
    output_file=file.path(dirname(input_file), out_dir, 'regular_expressions.md')) })
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, fig.align=TRUE)
options(width=125)
```

# Regular Expressions

###### Published: 11 April 2020

```{r}
setwd("~/CDAR")
beer <- read.csv("data/beer_cleaned.csv")
```

```{r}
length(levels(beer$style))
```

```{r}
levels(beer$style)
```

```{r}
sum(grepl("stout", beer$style, ignore.case=TRUE))
sum(grepl("[Ss]tout", beer$style))
```

```{r}
beer_style <- as.character(beer$style)

beer_style <- gsub(".*Stout.*", "Stout", beer_style)

sum(beer_style == "Stout")
unique(beer_style)
```

```{r}
regex.list <- c("Tripel|Dubbel|Quad.*|Belgian.*")

beer_style <- sapply(regex.list, function(x) gsub(x, "Belgian", beer_style))
unique(beer_style)
```


```{r}
beer_style <- as.character(beer$style)

sub.list <- c("Stout", "Porter", "IPA")
regex.list <- paste0(".*", sub.list, ".*")

sub.list
regex.list


# beer_style <- sapply(regex.list, function(x) gsub(x, sub.list[regex.list[x]], beer_style))
# beer_style

beer_styles <- mapply(function(x, y) gsub(x, y, beer_style), 
                     x=regex.list, y=sub.list)
unique(beer_styles)


beer_style <- gsub(regex.list, sub.list, beer_style)
beer_style <- sapply()


```

[Cascade approach](https://stat.ethz.ch/pipermail/r-help/2008-June/163634.html)

```{r}
beer_style_cascade <- gsub(regex.list[1], sub.list[1], 
                           gsub(regex.list[2], sub.list[2], 
                                gsub(regex.list[3], sub.list[3], beer_style)))
unique(beer_style_cascade)
```

For loop approach

```{r}
for(i in seq_along(regex.list)){beer_style <- gsub(regex.list[i], sub.list[i], beer_style)}
unique(beer_style)
```


[mgsub](http://thug-r.life/post/2018-01-10-safe-multiple-string-substitutions/)

```{r}
library(mgsub)

beer_style <- mgsub(beer_style, regex.list, sub.list)
unique(beer_style)


```


### Other Resources

[Basic Regular Expressions in R Cheat Sheet](https://rstudio.com/wp-content/uploads/2016/09/RegExCheatsheet.pdf)
